name: Feature Branch Workflow
on:
  pull_request:
    types: ['opened', 'edited']
jobs:
  deploy:
    name: Netlify deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: 'dist'
